# Generated by Django 5.2.1 on 2025-05-19 16:47

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('stock_id', models.CharField(max_length=50, unique=True)),
                ('km', models.PositiveIntegerField()),
                ('price', models.FloatField(help_text='Price of the vehicle')),
                ('make', models.CharField(max_length=100)),
                ('model', models.CharField(max_length=100)),
                ('year', models.PositiveIntegerField()),
                ('version', models.CharField(blank=True, max_length=100)),
                ('bluetooth', models.BooleanField(default=False)),
                ('car_play', models.BooleanField(default=False)),
                ('largo', models.FloatField(help_text='Length of the vehicle')),
                ('ancho', models.FloatField(help_text='Width of the vehicle')),
                ('altura', models.FloatField(help_text='Height of the vehicle')),
            ],
        ),
    ]
