# Generated by Django 5.2.1 on 2025-05-20 23:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_knowledgearticle'),
    ]

    operations = [
        migrations.AddField(
            model_name='knowledgearticle',
            name='url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
