# Generated by Django 5.2.1 on 2025-05-20 23:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_knowledgearticle_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='knowledgearticle',
            name='text',
            field=models.TextField(blank=True, null=True),
        ),
    ]
